version: '3'

services:
  nexus:
    container_name: nexuscache
    build: .
    ports:
      - "8978:8978"
    environment:
      PUID: 1000
      PGID: 1000
      REAL_DEBRID_API_TOKEN: RD_API_KEY
      API_URL: API_URL # nexus url
    networks: 
      - nexus

networks: 
  nexus:
    external: true
