version: '3.9'

services:
  nexus:
    image: pukabyte/nexus:latest
    build: .
    container_name: nexus
    restart: no
    ports:
      - "8978:8978"
    environment:
      PUID: 1000
      PGID: 1000
      RD_KEY: ${RD_KEY:-YOUR_RD_KEY}
    networks:
      - nexus

networks:
  nexus:
